aggregator:
  settings:
    best_state_path: save/best.pbuf
    db_store_rounds: 1
    init_state_path: save/init.pbuf
    last_state_path: save/last.pbuf
    rounds_to_train: 5
    write_logs: true
  template: openfl.component.Aggregator
assigner:
  settings:
    task_groups:
    - name: train_and_validate
      percentage: 1.0
      tasks:
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
  template: openfl.component.RandomGroupedAssigner
collaborator:
  settings:
    db_store_rounds: 1
    delta_updates: false
    opt_treatment: RESET
  template: openfl.component.Collaborator
compression_pipeline:
  settings:
    n_clusters: 2
  template: openfl.pipelines.NoCompressionPipeline
data_loader:
  settings:
    batch_size: 128
    collaborator_count: 2
    data_group_name: Anomalous_data
    data_path: data/Anomalous_data/ #I dont use this
    timesteps: 20
  template: src.kerasLSTM_inmemory.KerasLSTMInMemory
network:
  settings:
    #agg_addr: 172.16.234.181 #lab PC
    agg_addr: 192.168.1.24 #lab testbed new
    #agg_addr: 192.168.1.23 # lab testbed
    #agg_addr: 172.18.63.17 # my PC with GPU
    agg_port: 8080
    cert_folder: cert
    client_reconnect_interval: 5
    disable_client_auth: true
    hash_salt: auto
    tls: false
  template: openfl.federation.Network
task_runner:
  settings:
    input_shape:
    - 20
    - 4
  template: src.keras_LSTM.KerasLSTM
tasks:
  aggregated_model_validation:
    function: validate
    kwargs:
      apply: global
      batch_size: 32
      metrics:
      - root_mean_squared_error
  locally_tuned_model_validation:
    function: validate
    kwargs:
      apply: local
      batch_size: 32
      metrics:
      - root_mean_squared_error
  settings: {}
  train:
    function: train
    aggregation_type:
      template: openfl.interface.aggregation_functions.WeightedAverage
    #Predefined Aggregation Functions: https://openfl.readthedocs.io/en/latest/developer_guide/advanced_topics/overriding_agg_fn.html
    kwargs:
      batch_size: 128
      epochs: 10
      metrics:
      - root_mean_squared_error